name: CI Smoke Build  # GRAZYNKA CI v1 (no cache, no lockfile)

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20   # ← bez "cache: npm"

      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Build
        run: npm run build
