name: CI Smoke Build

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # UWAGA: bez cache, żeby nie wymagał lockfile'a
          # cache: 'npm'

      - name: Install deps
        run: |
          npm ci || npm install --no-audit --no-fund

      - name: Build
        run: npm run build
